$IF QB64CC_TYPES_STRING_EMPTY=UNDEFINED THEN
$LET QB64CC_TYPES_STRING_EMPTY=DEFINED

$IF QB64CC_TYPES_STRING=UNDEFINED THEN
$ERROR expected: 'String.bi'
$ENDIF

function String.EMPTY$()
	String.EMPTY = ""
end function

$ENDIF
