$IF QBTYPES_CHAR_ACCENT=UNDEFINED THEN
$LET QBTYPES_CHAR_ACCENT=DEFINED

$IF QBTYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.ACCENT$()
	Char.ACCENT = Char.from(96)
end function

$ENDIF
