$IF QBTYPES_CHAR_NEWLINE=UNDEFINED THEN
$LET QBTYPES_CHAR_NEWLINE=DEFINED

$IF QBTYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.NEWLINE$()
	Char.NEWLINE = Char.from(13)
end function

$ENDIF
