$IF QBTYPES_CHAR_SIX=UNDEFINED THEN
$LET QBTYPES_CHAR_SIX=DEFINED

$IF QBTYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.SIX$()
	Char.SIX = Char.from(54)
end function

$ENDIF
