$IF QB64CC_SYSTEM_CONSOLE_READKEY=UNDEFINED THEN
$LET QB64CC_SYSTEM_CONSOLE_READKEY=DEFINED

$IF QB64CC_SYSTEM_CONSOLE=UNDEFINED THEN
$ERROR expected: 'Console.bi'
$ENDIF

function Console.readKey$()
	Console.readKey = inkey$
end function

$ENDIF
