$IF QBCC_LISTS_STRINGLIST_CLEAR=UNDEFINED THEN
$LET QBCC_LISTS_STRINGLIST_CLEAR=DEFINED

$IF QBCC_LISTS_STRINGLIST=UNDEFINED THEN
$ERROR expected: 'StringList.bi'
$ENDIF

sub StringList.clear(this as StringList)
	this.value = ""
end sub

$ENDIF
