$IF QBCC_LISTS_LONGLIST_CLEAR=UNDEFINED THEN
$LET QBCC_LISTS_LONGLIST_CLEAR=DEFINED

$IF QBCC_LISTS_LONGLIST=UNDEFINED THEN
$ERROR expected: 'LongList.bi'
$ENDIF

sub LongList.clear(this as LongList)
	TList.clear this.value
end sub

$ENDIF
