$IF QB64CC_LISTS_LONGLIST_CLEAR=UNDEFINED THEN
$LET QB64CC_LISTS_LONGLIST_CLEAR=DEFINED

$IF QB64CC_LISTS_LONGLIST=UNDEFINED THEN
$ERROR expected: 'LongList.bi'
$ENDIF

sub LongList.clear(this as LongList)
	TList.clear this.value
end sub

$ENDIF
