$IF QBCC_SYSTEM_COLOR_LIGHTGREEN=UNDEFINED THEN
$LET QBCC_SYSTEM_COLOR_LIGHTGREEN=DEFINED

$IF QBCC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.LIGHTGREEN&()
	Color.LIGHTGREEN = Color.of(127, 255, 127)
end function

$ENDIF
