$IF QBCC_SYSTEM_COLOR_WHITE=UNDEFINED THEN
$LET QBCC_SYSTEM_COLOR_WHITE=DEFINED

$IF QBCC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.WHITE&()
	Color.WHITE = Color.of(255, 255, 255)
end function

$ENDIF
