$IF QBCC_LISTS=UNDEFINED THEN
$LET QBCC_LISTS=DEFINED

$IF QBCC_SYSTEM=UNDEFINED THEN
$ERROR expected:'System.bi'
$ENDIF

'$INCLUDE:'Lists/TList.bi'

'$INCLUDE:'Lists/LongList.bi'
'$INCLUDE:'Lists/StringList.bi'

$ENDIF
