$IF QB64CC_UTILS_MATH_E=UNDEFINED THEN
$LET QB64CC_UTILS_MATH_E=DEFINED

$IF QB64CC_UTILS_MATH=UNDEFINED THEN
$ERROR expected: 'Math.bi'
$ENDIF

function Math.E##()
	Math.E = exp(1##)
end function

$ENDIF
