$IF QB64CC_UTILS_MATH_PI=UNDEFINED THEN
$LET QB64CC_UTILS_MATH_PI=DEFINED

$IF QB64CC_UTILS_MATH=UNDEFINED THEN
$ERROR expected: 'Math.bi'
$ENDIF

function Math.PI##()
	Math.PI = 4## * atn(1##)
	'Math.PI = _pi
end function

$ENDIF
