$IF QB64CC_UTILS_MATH_RECIPROCAL=UNDEFINED THEN
$LET QB64CC_UTILS_MATH_RECIPROCAL=DEFINED

$IF QB64CC_UTILS_MATH=UNDEFINED THEN
$ERROR expected: 'Math.bi'
$ENDIF

function Math.Reciprocal##(this##)
	Math.Reciprocal = 1## / this##
end function

$ENDIF
