$IF QB64CC_UTILS_MATH_SIGN=UNDEFINED THEN
$LET QB64CC_UTILS_MATH_SIGN=DEFINED

$IF QB64CC_UTILS_MATH=UNDEFINED THEN
$ERROR expected: 'Math.bi'
$ENDIF

function Math.Sign%(this##)
	Math.Sign = sgn(this##)
end function

$ENDIF
