$IF QB64CC_TYPES_BYTE=UNDEFINED THEN
$LET QB64CC_TYPES_BYTE=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qb64cc.bi'
$ENDIF

'$INCLUDE:'Byte\if.bi'
'$INCLUDE:'Byte\toString.bi'
'$INCLUDE:'Byte\valueOf.bi'

$ENDIF
