$IF QBCC_TYPES_BYTE=UNDEFINED THEN
$LET QBCC_TYPES_BYTE=DEFINED

$IF QBCC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Byte\if.bi'
'$INCLUDE:'Byte\toString.bi'
'$INCLUDE:'Byte\valueOf.bi'

$ENDIF
