$IF QB64CC_TYPES_CHARS=UNDEFINED THEN
$LET QB64CC_TYPES_CHARS=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qb64cc.bi'
$ENDIF

'$INCLUDE:'Chars\areEqual.bi'
'$INCLUDE:'Chars\contain.bi'
'$INCLUDE:'Chars\indexOf.bi'
'$INCLUDE:'Chars\lastIndexOf.bi'

$ENDIF
