$IF QB64CC_TYPES_DOUBLE=UNDEFINED THEN
$LET QB64CC_TYPES_DOUBLE=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Double\if.bi'
'$INCLUDE:'Double\toString.bi'
'$INCLUDE:'Double\valueOf.bi'

$ENDIF
