$IF QB64CC_TYPES_FLOAT=UNDEFINED THEN
$LET QB64CC_TYPES_FLOAT=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Float\if.bi'
'$INCLUDE:'Float\toString.bi'
'$INCLUDE:'Float\valueOf.bi'

$ENDIF
