$IF QBCC_TYPES_FLOAT=UNDEFINED THEN
$LET QBCC_TYPES_FLOAT=DEFINED

$IF QBCC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Float\if.bi'
'$INCLUDE:'Float\toString.bi'
'$INCLUDE:'Float\valueOf.bi'

$ENDIF
