$IF QB64CC_TYPES_INTEGER=UNDEFINED THEN
$LET QB64CC_TYPES_INTEGER=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qb64cc.bi'
$ENDIF

'$INCLUDE:'Integer\if.bi'
'$INCLUDE:'Integer\toString.bi'
'$INCLUDE:'Integer\valueOf.bi'

$ENDIF
