$IF QBCC_TYPES_INTEGER=UNDEFINED THEN
$LET QBCC_TYPES_INTEGER=DEFINED

$IF QBCC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Integer\if.bi'
'$INCLUDE:'Integer\toString.bi'
'$INCLUDE:'Integer\valueOf.bi'

$ENDIF
