$IF QBCC_TYPES_LONG=UNDEFINED THEN
$LET QBCC_TYPES_LONG=DEFINED

$IF QBCC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Long\if.bi'
'$INCLUDE:'Long\toString.bi'
'$INCLUDE:'Long\valueOf.bi'

$ENDIF
