$IF QB64CC_TYPES_LONG=UNDEFINED THEN
$LET QB64CC_TYPES_LONG=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qb64cc.bi'
$ENDIF

'$INCLUDE:'Long\if.bi'
'$INCLUDE:'Long\toString.bi'
'$INCLUDE:'Long\valueOf.bi'

$ENDIF
