$IF QB64CC_TYPES_REALS=UNDEFINED THEN
$LET QB64CC_TYPES_REALS=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Reals\areEqual.bi'
'$INCLUDE:'Reals\contain.bi'
'$INCLUDE:'Reals\indexOf.bi'
'$INCLUDE:'Reals\lastIndexOf.bi'

$ENDIF
