$IF QBCC_TYPES_SHORT=UNDEFINED THEN
$LET QBCC_TYPES_SHORT=DEFINED

$IF QBCC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Short\if.bi'
'$INCLUDE:'Short\toString.bi'
'$INCLUDE:'Short\valueOf.bi'

$ENDIF
