$IF QB64CC_TYPES_SHORT=UNDEFINED THEN
$LET QB64CC_TYPES_SHORT=DEFINED

$IF QB64CC_TYPES=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

'$INCLUDE:'Short\if.bi'
'$INCLUDE:'Short\toString.bi'
'$INCLUDE:'Short\valueOf.bi'

$ENDIF
