$IF QB64CC_LISTS_TLIST_TOSTRING=UNDEFINED THEN
$LET QB64CC_LISTS_TLIST_TOSTRING=DEFINED

$IF QB64CC_LISTS_TLIST=UNDEFINED THEN
$ERROR expected: 'TList.bi'
$ENDIF

function TList.toString$(this as TList)
	TList.toString = this.value
end function

$ENDIF
