$IF QB64CC_UNITTEST_ASSERT=UNDEFINED THEN
$LET QB64CC_UNITTEST_ASSERT=DEFINED

$IF QB64CC_UNITTEST=UNDEFINED THEN
$ERROR expected: 'UnitTest.bi'
$ENDIF

$ASSERTS:CONSOLE

'$INCLUDE:'Assert/that.bi'

$ENDIF
