$IF QBCC_UNITTEST_ASSERT=UNDEFINED THEN
$LET QBCC_UNITTEST_ASSERT=DEFINED

$IF QBCC_UNITTEST=UNDEFINED THEN
$ERROR expected: 'UnitTest.bi'
$ENDIF

$ASSERTS:CONSOLE

'$INCLUDE:'Assert/that.bi'

$ENDIF
