$IF QB64CC_TYPES_CHAR_ACCENT=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_ACCENT=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.ACCENT$()
	Char.ACCENT = Char.from(96)
end function

$ENDIF
