$IF QBCC_TYPES_CHAR_ACCENT=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_ACCENT=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.ACCENT$()
	Char.ACCENT = Char.from(96)
end function

$ENDIF
