$IF QBCC_TYPES_CHAR_APOSTROPHE=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_APOSTROPHE=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.APOSTROPHE$()
	Char.APOSTROPHE = Char.from(39)
end function

$ENDIF
