$IF QBTYPES_CHAR_APOSTROPHE=UNDEFINED THEN
$LET QBTYPES_CHAR_APOSTROPHE=DEFINED

$IF QBTYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.APOSTROPHE$()
	Char.APOSTROPHE = Char.from(39)
end function

$ENDIF
