$IF QBCC_TYPES_CHAR_AT=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_AT=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.AT$()
	Char.AT = Char.from(64)
end function

$ENDIF
