$IF QB64CC_TYPES_CHAR_FIVE=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_FIVE=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.FIVE$()
	Char.FIVE = Char.from(53)
end function

$ENDIF
