$IF QBCC_TYPES_CHAR_FIVE=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_FIVE=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.FIVE$()
	Char.FIVE = Char.from(53)
end function

$ENDIF
