$IF QB64CC_TYPES_CHAR_FOUR=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_FOUR=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.FOUR$()
	Char.FOUR = Char.from(52)
end function

$ENDIF
