$IF QB64CC_TYPES_CHAR_NEWLINE=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_NEWLINE=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.NEWLINE$()
	Char.NEWLINE = Char.from(13)
end function

$ENDIF
