$IF QB64CC_TYPES_CHAR_NINE=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_NINE=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.NINE$()
	Char.NINE = Char.from(57)
end function

$ENDIF
