$IF QBCC_TYPES_CHAR_NINE=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_NINE=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.NINE$()
	Char.NINE = Char.from(57)
end function

$ENDIF
