$IF QB64CC_TYPES_CHAR_NULL=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_NULL=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.NULL$()
	Char.NULL = Char.from(0)
end function

$ENDIF
