$IF QBCC_TYPES_CHAR_ONE=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_ONE=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.ONE$()
	Char.ONE = Char.from(49)
end function

$ENDIF
