$IF QBCC_TYPES_CHAR_QUOTE=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_QUOTE=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.QUOTE$()
	Char.QUOTE = Char.from(34)
end function

$ENDIF
