$IF QB64CC_TYPES_CHAR_QUOTE=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_QUOTE=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.QUOTE$()
	Char.QUOTE = Char.from(34)
end function

$ENDIF
