$IF QBCC_TYPES_CHAR_SEVEN=UNDEFINED THEN
$LET QBCC_TYPES_CHAR_SEVEN=DEFINED

$IF QBCC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.SEVEN$()
	Char.SEVEN = Char.from(55)
end function

$ENDIF
