$IF QB64CC_TYPES_CHAR_SIX=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_SIX=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.SIX$()
	Char.SIX = Char.from(54)
end function

$ENDIF
