$IF QB64CC_TYPES_CHAR_SPACE=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_SPACE=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.SPACE$()
	Char.SPACE = Char.from(32)
end function

$ENDIF
