$IF QB64CC_TYPES_CHAR_THREE=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_THREE=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.THREE$()
	Char.THREE = Char.from(51)
end function

$ENDIF
