$IF QB64CC_TYPES_CHAR_ZERO=UNDEFINED THEN
$LET QB64CC_TYPES_CHAR_ZERO=DEFINED

$IF QB64CC_TYPES_CHAR=UNDEFINED THEN
$ERROR expected: 'Char.bi'
$ENDIF

function Char.ZERO$()
	Char.ZERO = Char.from(48)
end function

$ENDIF
