$IF QB64CC_SYSTEM_COLOR_BLACK=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_BLACK=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.BLACK&()
	Color.BLACK = Color.of(0, 0, 0)
end function

$ENDIF
