$IF QB64CC_SYSTEM_COLOR_BROWN=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_BROWN=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.BROWN&()
	Color.BROWN = Color.of(127, 63, 0)
end function

$ENDIF
