$IF QBCC_COLOR_DARKGREEN=UNDEFINED THEN
$LET QBCC_COLOR_DARKGREEN=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKGREEN&()
	Color.DARKGREEN = Color.of(0, 127, 0)
end function

$ENDIF
