$IF QBCC_COLOR_DARKGRAY=UNDEFINED THEN
$LET QBCC_COLOR_DARKGRAY=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKGRAY&()
	Color.DARKGRAY = Color.of(85, 85, 85)
end function

$ENDIF
