$IF QB64CC_SYSTEM_COLOR_DARKGRAY=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_DARKGRAY=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKGRAY&()
	Color.DARKGRAY = Color.of(85, 85, 85)
end function

$ENDIF
