$IF QBCC_COLOR_DARKCYAN=UNDEFINED THEN
$LET QBCC_COLOR_DARKCYAN=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKCYAN&()
	Color.DARKCYAN = Color.of(0, 127, 127)
end function

$ENDIF
