$IF QB64CC_SYSTEM_COLOR_DARKGREEN=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_DARKGREEN=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKGREEN&()
	Color.DARKGREEN = Color.of(0, 127, 0)
end function

$ENDIF
