$IF QBCC_COLOR_DARKBLUE=UNDEFINED THEN
$LET QBCC_COLOR_DARKBLUE=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKBLUE&()
	Color.DARKBLUE = Color.of(0, 0, 127)
end function

$ENDIF
