$IF QBCC_COLOR_DARKGREY=UNDEFINED THEN
$LET QBCC_COLOR_DARKGREY=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKGREY&()
	Color.DARKGREY = Color.of(85, 85, 85)
end function

$ENDIF
