$IF QB64CC_SYSTEM_COLOR_DARKCYAN=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_DARKCYAN=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKCYAN&()
	Color.DARKCYAN = Color.of(0, 127, 127)
end function

$ENDIF
