$IF QB64CC_SYSTEM_COLOR_DARKGREY=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_DARKGREY=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKGREY&()
	Color.DARKGREY = Color.of(85, 85, 85)
end function

$ENDIF
