$IF QB64CC_SYSTEM_COLOR_DARKRED=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_DARKRED=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DARKRED&()
	Color.DARKRED = Color.of(127, 0, 0)
end function

$ENDIF
