$IF QB64CC_SYSTEM_COLOR_DEFAULT=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_DEFAULT=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DEFAULT&()
	Color.DEFAULT = -1
end function

$ENDIF
