$IF QBCC_COLOR_DEFAULT=UNDEFINED THEN
$LET QBCC_COLOR_DEFAULT=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.DEFAULT&()
	Color.DEFAULT = -1
end function

$ENDIF
