$IF QB64CC_SYSTEM_COLOR_GREEN=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_GREEN=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.GREEN&()
	Color.GREEN = Color.of(0, 255, 0)
end function

$ENDIF
