$IF QB64CC_SYSTEM_COLOR_GREY=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_GREY=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.GREY&()
	Color.GREY = Color.of(127, 127, 127)
end function

$ENDIF
