$IF QB64CC_SYSTEM_COLOR_LIGHTRED=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_LIGHTRED=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.LIGHTRED&()
	Color.LIGHTRED = Color.of(255, 127, 127)
end function

$ENDIF
