$IF QB64CC_SYSTEM_COLOR_LIGHTGREY=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_LIGHTGREY=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.LIGHTGREY&()
	Color.LIGHTGREY = Color.of(170, 170, 170)
end function

$ENDIF
