$IF QB64CC_SYSTEM_COLOR_LIGHTCYAN=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_LIGHTCYAN=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.LIGHTCYAN&()
	Color.LIGHTCYAN = Color.of(127, 255, 255)
end function

$ENDIF
