$IF QB64CC_SYSTEM_COLOR_LIGHTMAGENTA=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_LIGHTMAGENTA=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.LIGHTMAGENTA&()
	Color.LIGHTMAGENTA = Color.of(255, 127, 255)
end function

$ENDIF
