$IF QB64CC_SYSTEM_COLOR_LIGHTGRAY=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_LIGHTGRAY=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.LIGHTGRAY&()
	Color.LIGHTGRAY = Color.of(170, 170, 170)
end function

$ENDIF
