$IF QB64CC_SYSTEM_COLOR_PURPLE=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_PURPLE=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.PURPLE&()
	Color.PURPLE = Color.of(255, 0, 127)
end function

$ENDIF
