$IF QBCC_COLOR_RED=UNDEFINED THEN
$LET QBCC_COLOR_RED=DEFINED

$IF QBCC_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.RED&()
	Color.RED = Color.of(255, 0, 0)
end function

$ENDIF
