$IF QB64CC_SYSTEM_COLOR_RED=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_RED=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.RED&()
	Color.RED = Color.of(255, 0, 0)
end function

$ENDIF
