$IF QB64CC_SYSTEM_COLOR_YELLOW=UNDEFINED THEN
$LET QB64CC_SYSTEM_COLOR_YELLOW=DEFINED

$IF QB64CC_SYSTEM_COLOR=UNDEFINED THEN
$ERROR expected: 'Color.bi'
$ENDIF

function Color.YELLOW&()
	Color.YELLOW = Color.of(255, 255, 0)
end function

$ENDIF
