$IF QBCC_LISTS_TLIST_CLEAR=UNDEFINED THEN
$LET QBCC_LISTS_TLIST_CLEAR=DEFINED

$IF QBCC_LISTS_TLIST=UNDEFINED THEN
$ERROR expected: 'TList.bi'
$ENDIF

sub TList.clear(this as TList)
	this.value = ""
end sub

$ENDIF
