$IF QB64CC_LISTS_TLIST_CLEAR=UNDEFINED THEN
$LET QB64CC_LISTS_TLIST_CLEAR=DEFINED

$IF QB64CC_LISTS_TLIST=UNDEFINED THEN
$ERROR expected: 'TList.bi'
$ENDIF

sub TList.clear(this as TList)
	this.value = ""
end sub

$ENDIF
