$IF QBCC_LISTS_TLIST_INDEXOUTOFBOUNDSEXCE_00=UNDEFINED THEN
$LET QBCC_LISTS_TLIST_INDEXOUTOFBOUNDSEXCE_00=DEFINED

$IF QBCC_LISTS_TLIST=UNDEFINED THEN
$ERROR expected: 'TList.bi'
$ENDIF

function TList.IndexOutOfBoundsException%()
	TList.IndexOutOfBoundsException = 9
end function

$ENDIF
