$IF QBLISTS_TLIST_INDEXOUTOFBOUNDSEXCEPTION=UNDEFINED THEN
$LET QBLISTS_TLIST_INDEXOUTOFBOUNDSEXCEPTION=DEFINED

$IF QBLISTS_TLIST=UNDEFINED THEN
$ERROR expected: 'TList.bi'
$ENDIF

function TList.IndexOutOfBoundsException%()
	TList.IndexOutOfBoundsException = 9
end function

$ENDIF
