$IF QB64CC_SYSTEM_EXCEPTION_ISDUPLICATEDEFINITION=UNDEFINED THEN
$LET QB64CC_SYSTEM_EXCEPTION_ISDUPLICATEDEFINITION=DEFINED

$IF QB64CC_SYSTEM_EXCEPTION=UNDEFINED THEN
$ERROR expected: 'Exception.bi'
$ENDIF

function Exception.isDuplicateDefinition%%()
	Exception.isDuplicateDefinition = Exception.is(10)
end function

$ENDIF
