$IF QB64CC_SYSTEM_EXCEPTION_ISILLEGALFUNCTIONCALL=UNDEFINED THEN
$LET QB64CC_SYSTEM_EXCEPTION_ISILLEGALFUNCTIONCALL=DEFINED

$IF QB64CC_SYSTEM=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

function Exception.isIllegalFunctionCall%%()
	Exception.isIllegalFunctionCall = Exception.is(5)
end function

$ENDIF
