$IF QB64CC_SYSTEM_EXCEPTION_ISNOERROR=UNDEFINED THEN
$LET QB64CC_SYSTEM_EXCEPTION_ISNOERROR=DEFINED

$IF QB64CC_SYSTEM_EXCEPTION=UNDEFINED THEN
$ERROR expected: 'Exception.bi'
$ENDIF

function Exception.isNoError%%()
	Exception.isNoError = Exception.is(0)
end function

$ENDIF
