$IF QB64CC_SYSTEM_EXCEPTION_ISOVERFLOW=UNDEFINED THEN
$LET QB64CC_SYSTEM_EXCEPTION_ISOVERFLOW=DEFINED

$IF QB64CC_SYSTEM=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

function Exception.isOverflow%%()
	Exception.isOverflow = Exception.is(6)
end function

$ENDIF
