$IF QBCC_SYSTEM_EXCEPTION_TOSTRING=UNDEFINED THEN
$LET QBCC_SYSTEM_EXCEPTION_TOSTRING=DEFINED

$IF QBCC_SYSTEM=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

function Exception.toString$(this as Exceprtion)

end function

$ENDIF
