$IF QB64CC_SYSTEM_EXCEPTION_TOSTRING=UNDEFINED THEN
$LET QB64CC_SYSTEM_EXCEPTION_TOSTRING=DEFINED

$IF QB64CC_SYSTEM=UNDEFINED THEN
$ERROR expected: 'qbcc.bi'
$ENDIF

function Exception.toString$(this as Exceprtion)

end function

$ENDIF
